TITLE Mod file for component: Component(id=GolgiSK2 type=ionChannelKS)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.5.4
         org.neuroml.model   v1.5.4
         jLEMS               v0.9.9.1

ENDCOMMENT

NEURON {
    SUFFIX GolgiSK2
    USEION ca READ cai,cao VALENCE 2
    USEION k WRITE ik VALENCE 1 ? Assuming valence = 1; TODO check this!!
    
    RANGE gion                           
    RANGE gmax                              : Will be changed when ion channel mechanism placed on cell!
    RANGE conductance                       : parameter
    
    RANGE g                                 : exposure
    
    RANGE fopen                             : exposure
    RANGE n_instances                       : parameter
    
    RANGE n_rateScale                       : exposure
    
    RANGE n_fcond                           : exposure
    
    RANGE n_q                               : exposure
    RANGE n_q10Settings_q10Factor           : parameter
    RANGE n_q10Settings_experimentalTemp    : parameter
    RANGE n_q10Settings_TENDEGREES          : parameter
    
    RANGE n_q10Settings_q10                 : exposure
    RANGE n_c1_relativeConductance          : parameter
    
    RANGE n_c1_q                            : exposure
    RANGE n_c2_relativeConductance          : parameter
    
    RANGE n_c2_q                            : exposure
    RANGE n_c3_relativeConductance          : parameter
    
    RANGE n_c3_q                            : exposure
    RANGE n_c4_relativeConductance          : parameter
    
    RANGE n_c4_q                            : exposure
    RANGE n_o1_relativeConductance          : parameter
    
    RANGE n_o1_q                            : exposure
    RANGE n_o2_relativeConductance          : parameter
    
    RANGE n_o2_q                            : exposure
    RANGE n_alpha_c1_c2_SEC                 : parameter
    
    RANGE n_alpha_c1_c2_rf                  : exposure
    
    RANGE n_alpha_c1_c2_rr                  : exposure
    RANGE n_alpha_c1_c2_rate_scale          : parameter
    RANGE n_alpha_c1_c2_rate_diff           : parameter
    RANGE n_alpha_c1_c2_rate_CONC_SCALE     : parameter
    
    RANGE n_alpha_c1_c2_rate_r              : exposure
    RANGE n_beta_c1_c2_SEC                  : parameter
    
    RANGE n_beta_c1_c2_rf                   : exposure
    
    RANGE n_beta_c1_c2_rr                   : exposure
    RANGE n_beta_c1_c2_rate_scale           : parameter
    
    RANGE n_beta_c1_c2_rate_r               : exposure
    RANGE n_alpha_c2_c3_SEC                 : parameter
    
    RANGE n_alpha_c2_c3_rf                  : exposure
    
    RANGE n_alpha_c2_c3_rr                  : exposure
    RANGE n_alpha_c2_c3_rate_scale          : parameter
    RANGE n_alpha_c2_c3_rate_diff           : parameter
    RANGE n_alpha_c2_c3_rate_CONC_SCALE     : parameter
    
    RANGE n_alpha_c2_c3_rate_r              : exposure
    RANGE n_beta_c2_c3_SEC                  : parameter
    
    RANGE n_beta_c2_c3_rf                   : exposure
    
    RANGE n_beta_c2_c3_rr                   : exposure
    RANGE n_beta_c2_c3_rate_scale           : parameter
    
    RANGE n_beta_c2_c3_rate_r               : exposure
    RANGE n_alpha_c3_c4_SEC                 : parameter
    
    RANGE n_alpha_c3_c4_rf                  : exposure
    
    RANGE n_alpha_c3_c4_rr                  : exposure
    RANGE n_alpha_c3_c4_rate_scale          : parameter
    RANGE n_alpha_c3_c4_rate_diff           : parameter
    RANGE n_alpha_c3_c4_rate_CONC_SCALE     : parameter
    
    RANGE n_alpha_c3_c4_rate_r              : exposure
    RANGE n_beta_c3_c4_SEC                  : parameter
    
    RANGE n_beta_c3_c4_rf                   : exposure
    
    RANGE n_beta_c3_c4_rr                   : exposure
    RANGE n_beta_c3_c4_rate_scale           : parameter
    
    RANGE n_beta_c3_c4_rate_r               : exposure
    RANGE n_alpha_c3_o1_SEC                 : parameter
    
    RANGE n_alpha_c3_o1_rf                  : exposure
    
    RANGE n_alpha_c3_o1_rr                  : exposure
    RANGE n_alpha_c3_o1_rate_scale          : parameter
    
    RANGE n_alpha_c3_o1_rate_r              : exposure
    RANGE n_beta_c3_o1_SEC                  : parameter
    
    RANGE n_beta_c3_o1_rf                   : exposure
    
    RANGE n_beta_c3_o1_rr                   : exposure
    RANGE n_beta_c3_o1_rate_scale           : parameter
    
    RANGE n_beta_c3_o1_rate_r               : exposure
    RANGE n_alpha_c4_o2_SEC                 : parameter
    
    RANGE n_alpha_c4_o2_rf                  : exposure
    
    RANGE n_alpha_c4_o2_rr                  : exposure
    RANGE n_alpha_c4_o2_rate_scale          : parameter
    
    RANGE n_alpha_c4_o2_rate_r              : exposure
    RANGE n_beta_c4_o2_SEC                  : parameter
    
    RANGE n_beta_c4_o2_rf                   : exposure
    
    RANGE n_beta_c4_o2_rr                   : exposure
    RANGE n_beta_c4_o2_rate_scale           : parameter
    
    RANGE n_beta_c4_o2_rate_r               : exposure
    RANGE n_alpha_c1_c2_rf0                 : derived variable
    RANGE n_beta_c1_c2_rr0                  : derived variable
    RANGE n_alpha_c2_c3_rf0                 : derived variable
    RANGE n_beta_c2_c3_rr0                  : derived variable
    RANGE n_alpha_c3_c4_rf0                 : derived variable
    RANGE n_beta_c3_c4_rr0                  : derived variable
    RANGE n_alpha_c3_o1_rf0                 : derived variable
    RANGE n_beta_c3_o1_rr0                  : derived variable
    RANGE n_alpha_c4_o2_rf0                 : derived variable
    RANGE n_beta_c4_o2_rr0                  : derived variable
    
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (S) = (siemens)
    
}

PARAMETER {
    
    gmax = 0  (S/cm2)                       : Will be changed when ion channel mechanism placed on cell!
    
    conductance = 1.0E-5 (uS)
    n_instances = 1 
    n_q10Settings_q10Factor = 3 
    n_q10Settings_experimentalTemp = 296.15 (K)
    n_q10Settings_TENDEGREES = 10 (K)
    n_c1_relativeConductance = 0 
    n_c2_relativeConductance = 0 
    n_c3_relativeConductance = 0 
    n_c4_relativeConductance = 0 
    n_o1_relativeConductance = 1 
    n_o2_relativeConductance = 1 
    n_alpha_c1_c2_SEC = 1000 (ms)
    n_alpha_c1_c2_rate_scale = 200.00002 (kHz)
    n_alpha_c1_c2_rate_diff = 3 
    n_alpha_c1_c2_rate_CONC_SCALE = 1 (mM)
    n_beta_c1_c2_SEC = 1000 (ms)
    n_beta_c1_c2_rate_scale = 0.080000006 (kHz)
    n_alpha_c2_c3_SEC = 1000 (ms)
    n_alpha_c2_c3_rate_scale = 160 (kHz)
    n_alpha_c2_c3_rate_diff = 3 
    n_alpha_c2_c3_rate_CONC_SCALE = 1 (mM)
    n_beta_c2_c3_SEC = 1000 (ms)
    n_beta_c2_c3_rate_scale = 0.080000006 (kHz)
    n_alpha_c3_c4_SEC = 1000 (ms)
    n_alpha_c3_c4_rate_scale = 80 (kHz)
    n_alpha_c3_c4_rate_diff = 3 
    n_alpha_c3_c4_rate_CONC_SCALE = 1 (mM)
    n_beta_c3_c4_SEC = 1000 (ms)
    n_beta_c3_c4_rate_scale = 0.2 (kHz)
    n_alpha_c3_o1_SEC = 1000 (ms)
    n_alpha_c3_o1_rate_scale = 0.16000001 (kHz)
    n_beta_c3_o1_SEC = 1000 (ms)
    n_beta_c3_o1_rate_scale = 1 (kHz)
    n_alpha_c4_o2_SEC = 1000 (ms)
    n_alpha_c4_o2_rate_scale = 1.2 (kHz)
    n_beta_c4_o2_SEC = 1000 (ms)
    n_beta_c4_o2_rate_scale = 0.1 (kHz)
}

ASSIGNED {
    
    gion   (S/cm2)                          : Transient conductance density of the channel? Standard Assigned variables with ionChannel
    v (mV)
    celsius (degC)
    temperature (K)
    ek (mV)
    ik (mA/cm2)
    
    cai (mM)
    
    cao (mM)
    
    
    n_q10Settings_q10                      : derived variable
    
    n_c1_q                                 : derived variable
    
    n_c2_q                                 : derived variable
    
    n_c3_q                                 : derived variable
    
    n_c4_q                                 : derived variable
    
    n_o1_q                                 : derived variable
    
    n_o2_q                                 : derived variable
    
    n_alpha_c1_c2_rate_r (kHz)             : derived variable
    
    n_alpha_c1_c2_rf0 (kHz)                : derived variable
    
    n_alpha_c1_c2_rf (kHz)                 : derived variable
    
    n_alpha_c1_c2_rr (kHz)                 : derived variable
    
    n_beta_c1_c2_rate_r (kHz)              : derived variable
    
    n_beta_c1_c2_rr0 (kHz)                 : derived variable
    
    n_beta_c1_c2_rr (kHz)                  : derived variable
    
    n_beta_c1_c2_rf (kHz)                  : derived variable
    
    n_alpha_c2_c3_rate_r (kHz)             : derived variable
    
    n_alpha_c2_c3_rf0 (kHz)                : derived variable
    
    n_alpha_c2_c3_rf (kHz)                 : derived variable
    
    n_alpha_c2_c3_rr (kHz)                 : derived variable
    
    n_beta_c2_c3_rate_r (kHz)              : derived variable
    
    n_beta_c2_c3_rr0 (kHz)                 : derived variable
    
    n_beta_c2_c3_rr (kHz)                  : derived variable
    
    n_beta_c2_c3_rf (kHz)                  : derived variable
    
    n_alpha_c3_c4_rate_r (kHz)             : derived variable
    
    n_alpha_c3_c4_rf0 (kHz)                : derived variable
    
    n_alpha_c3_c4_rf (kHz)                 : derived variable
    
    n_alpha_c3_c4_rr (kHz)                 : derived variable
    
    n_beta_c3_c4_rate_r (kHz)              : derived variable
    
    n_beta_c3_c4_rr0 (kHz)                 : derived variable
    
    n_beta_c3_c4_rr (kHz)                  : derived variable
    
    n_beta_c3_c4_rf (kHz)                  : derived variable
    
    n_alpha_c3_o1_rate_r (kHz)             : derived variable
    
    n_alpha_c3_o1_rf0 (kHz)                : derived variable
    
    n_alpha_c3_o1_rf (kHz)                 : derived variable
    
    n_alpha_c3_o1_rr (kHz)                 : derived variable
    
    n_beta_c3_o1_rate_r (kHz)              : derived variable
    
    n_beta_c3_o1_rr0 (kHz)                 : derived variable
    
    n_beta_c3_o1_rr (kHz)                  : derived variable
    
    n_beta_c3_o1_rf (kHz)                  : derived variable
    
    n_alpha_c4_o2_rate_r (kHz)             : derived variable
    
    n_alpha_c4_o2_rf0 (kHz)                : derived variable
    
    n_alpha_c4_o2_rf (kHz)                 : derived variable
    
    n_alpha_c4_o2_rr (kHz)                 : derived variable
    
    n_beta_c4_o2_rate_r (kHz)              : derived variable
    
    n_beta_c4_o2_rr0 (kHz)                 : derived variable
    
    n_beta_c4_o2_rr (kHz)                  : derived variable
    
    n_beta_c4_o2_rf (kHz)                  : derived variable
    
    n_rateScale                            : derived variable
    
    n_q                                    : derived variable
    
    n_fcond                                : derived variable
    
    fopen                                  : derived variable
    
    g (uS)                                 : derived variable
    
}

STATE {
    n_c1_occupancy FROM 0 TO 1  
    n_c2_occupancy FROM 0 TO 1  
    n_c3_occupancy FROM 0 TO 1  
    n_c4_occupancy FROM 0 TO 1  
    n_o1_occupancy FROM 0 TO 1  
    n_o2_occupancy FROM 0 TO 1  
    
}

INITIAL {
    ek = -84.69
    
    temperature = celsius + 273.15
    
    rates()
    rates() ? To ensure correct initialisation.
    SOLVE activation STEADYSTATE sparse
    
}

BREAKPOINT {
    
    SOLVE activation METHOD sparse ? GolgiSK2 (Type: ionChannelKS:  conductance=1.0E-11 (SI conductance))
    
    ? DerivedVariable is based on path: gates[*]/fcond, on: Component(id=GolgiSK2 type=ionChannelKS), from gates; Component(id=n type=gateKS)
    ? multiply applied to all instances of fcond in: <gates> ([Component(id=n type=gateKS)]))
    fopen = n_fcond ? path based, prefix = 
    
    g = fopen  *  conductance ? evaluable
    gion = gmax * fopen 
    
    ik = gion * (v - ek)
    
}

KINETIC activation {
    rates()
    
    ~ n_c1_occupancy <-> n_c2_occupancy    (n_alpha_c1_c2_rate_r,n_beta_c1_c2_rate_r)
    ~ n_c2_occupancy <-> n_c3_occupancy    (n_alpha_c2_c3_rate_r,n_beta_c2_c3_rate_r)
    ~ n_c3_occupancy <-> n_c4_occupancy    (n_alpha_c3_c4_rate_r,n_beta_c3_c4_rate_r)
    ~ n_c3_occupancy <-> n_o1_occupancy    (n_alpha_c3_o1_rate_r,n_beta_c3_o1_rate_r)
    ~ n_c4_occupancy <-> n_o2_occupancy    (n_alpha_c4_o2_rate_r,n_beta_c4_o2_rate_r)
    CONSERVE n_c1_occupancy+n_o1_occupancy+n_o2_occupancy+n_c3_occupancy+n_c4_occupancy+n_c2_occupancy= 1
    
    
}

PROCEDURE rates() {
    LOCAL caConc
    
    caConc = cai
    
    n_q10Settings_q10 = n_q10Settings_q10Factor ^((temperature -  n_q10Settings_experimentalTemp )/ n_q10Settings_TENDEGREES ) ? evaluable
    n_c1_q = n_c1_relativeConductance  *  n_c1_occupancy ? evaluable
    n_c2_q = n_c2_relativeConductance  *  n_c2_occupancy ? evaluable
    n_c3_q = n_c3_relativeConductance  *  n_c3_occupancy ? evaluable
    n_c4_q = n_c4_relativeConductance  *  n_c4_occupancy ? evaluable
    n_o1_q = n_o1_relativeConductance  *  n_o1_occupancy ? evaluable
    n_o2_q = n_o2_relativeConductance  *  n_o2_occupancy ? evaluable
    n_alpha_c1_c2_rate_r = n_rateScale  * ( n_alpha_c1_c2_rate_scale /  n_alpha_c1_c2_rate_CONC_SCALE  * (caConc/ n_alpha_c1_c2_rate_diff )) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=alpha_c1_c2 type=forwardTransition), from rate; Component(id=null type=cadep_rate)
    n_alpha_c1_c2_rf0 = n_alpha_c1_c2_rate_r ? path based, prefix = n_alpha_c1_c2_
    
    n_alpha_c1_c2_rf = n_alpha_c1_c2_rf0 ? evaluable
    n_alpha_c1_c2_rr = 0/ n_alpha_c1_c2_SEC ? evaluable
    n_beta_c1_c2_rate_r = n_rateScale  * ( n_beta_c1_c2_rate_scale ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=beta_c1_c2 type=reverseTransition), from rate; Component(id=null type=caindep_rate)
    n_beta_c1_c2_rr0 = n_beta_c1_c2_rate_r ? path based, prefix = n_beta_c1_c2_
    
    n_beta_c1_c2_rr = n_beta_c1_c2_rr0 ? evaluable
    n_beta_c1_c2_rf = 0/ n_beta_c1_c2_SEC ? evaluable
    n_alpha_c2_c3_rate_r = n_rateScale  * ( n_alpha_c2_c3_rate_scale /  n_alpha_c2_c3_rate_CONC_SCALE  * (caConc/ n_alpha_c2_c3_rate_diff )) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=alpha_c2_c3 type=forwardTransition), from rate; Component(id=null type=cadep_rate)
    n_alpha_c2_c3_rf0 = n_alpha_c2_c3_rate_r ? path based, prefix = n_alpha_c2_c3_
    
    n_alpha_c2_c3_rf = n_alpha_c2_c3_rf0 ? evaluable
    n_alpha_c2_c3_rr = 0/ n_alpha_c2_c3_SEC ? evaluable
    n_beta_c2_c3_rate_r = n_rateScale  * ( n_beta_c2_c3_rate_scale ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=beta_c2_c3 type=reverseTransition), from rate; Component(id=null type=caindep_rate)
    n_beta_c2_c3_rr0 = n_beta_c2_c3_rate_r ? path based, prefix = n_beta_c2_c3_
    
    n_beta_c2_c3_rr = n_beta_c2_c3_rr0 ? evaluable
    n_beta_c2_c3_rf = 0/ n_beta_c2_c3_SEC ? evaluable
    n_alpha_c3_c4_rate_r = n_rateScale  * ( n_alpha_c3_c4_rate_scale /  n_alpha_c3_c4_rate_CONC_SCALE  * (caConc/ n_alpha_c3_c4_rate_diff )) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=alpha_c3_c4 type=forwardTransition), from rate; Component(id=null type=cadep_rate)
    n_alpha_c3_c4_rf0 = n_alpha_c3_c4_rate_r ? path based, prefix = n_alpha_c3_c4_
    
    n_alpha_c3_c4_rf = n_alpha_c3_c4_rf0 ? evaluable
    n_alpha_c3_c4_rr = 0/ n_alpha_c3_c4_SEC ? evaluable
    n_beta_c3_c4_rate_r = n_rateScale  * ( n_beta_c3_c4_rate_scale ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=beta_c3_c4 type=reverseTransition), from rate; Component(id=null type=caindep_rate)
    n_beta_c3_c4_rr0 = n_beta_c3_c4_rate_r ? path based, prefix = n_beta_c3_c4_
    
    n_beta_c3_c4_rr = n_beta_c3_c4_rr0 ? evaluable
    n_beta_c3_c4_rf = 0/ n_beta_c3_c4_SEC ? evaluable
    n_alpha_c3_o1_rate_r = n_rateScale  * ( n_alpha_c3_o1_rate_scale ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=alpha_c3_o1 type=forwardTransition), from rate; Component(id=null type=caindep_rate)
    n_alpha_c3_o1_rf0 = n_alpha_c3_o1_rate_r ? path based, prefix = n_alpha_c3_o1_
    
    n_alpha_c3_o1_rf = n_alpha_c3_o1_rf0 ? evaluable
    n_alpha_c3_o1_rr = 0/ n_alpha_c3_o1_SEC ? evaluable
    n_beta_c3_o1_rate_r = n_rateScale  * ( n_beta_c3_o1_rate_scale ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=beta_c3_o1 type=reverseTransition), from rate; Component(id=null type=caindep_rate)
    n_beta_c3_o1_rr0 = n_beta_c3_o1_rate_r ? path based, prefix = n_beta_c3_o1_
    
    n_beta_c3_o1_rr = n_beta_c3_o1_rr0 ? evaluable
    n_beta_c3_o1_rf = 0/ n_beta_c3_o1_SEC ? evaluable
    n_alpha_c4_o2_rate_r = n_rateScale  * ( n_alpha_c4_o2_rate_scale ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=alpha_c4_o2 type=forwardTransition), from rate; Component(id=null type=caindep_rate)
    n_alpha_c4_o2_rf0 = n_alpha_c4_o2_rate_r ? path based, prefix = n_alpha_c4_o2_
    
    n_alpha_c4_o2_rf = n_alpha_c4_o2_rf0 ? evaluable
    n_alpha_c4_o2_rr = 0/ n_alpha_c4_o2_SEC ? evaluable
    n_beta_c4_o2_rate_r = n_rateScale  * ( n_beta_c4_o2_rate_scale ) ? evaluable
    ? DerivedVariable is based on path: rate/r, on: Component(id=beta_c4_o2 type=reverseTransition), from rate; Component(id=null type=caindep_rate)
    n_beta_c4_o2_rr0 = n_beta_c4_o2_rate_r ? path based, prefix = n_beta_c4_o2_
    
    n_beta_c4_o2_rr = n_beta_c4_o2_rr0 ? evaluable
    n_beta_c4_o2_rf = 0/ n_beta_c4_o2_SEC ? evaluable
    ? DerivedVariable is based on path: q10Settings[*]/q10, on: Component(id=n type=gateKS), from q10Settings; Component(id=null type=q10ExpTemp)
    ? multiply applied to all instances of q10 in: <q10Settings> ([Component(id=null type=q10ExpTemp)]))
    n_rateScale = n_q10Settings_q10 ? path based, prefix = n_
    
    ? DerivedVariable is based on path: states[*]/q, on: Component(id=n type=gateKS), from states; Component(id=c1 type=closedState)
    ? add applied to all instances of q in: <states> ([Component(id=c1 type=closedState), Component(id=c2 type=closedState), Component(id=c3 type=closedState), Component(id=c4 type=closedState), Component(id=o1 type=openState), Component(id=o2 type=openState)]))
    n_q = n_c1_q + n_c2_q + n_c3_q + n_c4_q + n_o1_q + n_o2_q ? path based, prefix = n_
    
    n_fcond = n_q ^ n_instances ? evaluable
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
}

