TITLE Mod file for component: Component(id=GolgiNaR type=ionChannelHH)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.5.4
         org.neuroml.model   v1.5.4
         jLEMS               v0.9.9.1

ENDCOMMENT

NEURON {
    SUFFIX GolgiNaR
    USEION na WRITE ina VALENCE 1 ? Assuming valence = 1; TODO check this!!
    
    RANGE gion                           
    RANGE gmax                              : Will be changed when ion channel mechanism placed on cell!
    RANGE conductance                       : parameter
    
    RANGE g                                 : exposure
    
    RANGE fopen                             : exposure
    RANGE s_instances                       : parameter
    
    RANGE s_alpha                           : exposure
    
    RANGE s_beta                            : exposure
    
    RANGE s_tau                             : exposure
    
    RANGE s_inf                             : exposure
    
    RANGE s_rateScale                       : exposure
    
    RANGE s_fcond                           : exposure
    RANGE s_forwardRate_rate                : parameter
    RANGE s_forwardRate_midpoint            : parameter
    RANGE s_forwardRate_scale               : parameter
    RANGE s_forwardRate_shift               : parameter
    
    RANGE s_forwardRate_r                   : exposure
    RANGE s_reverseRate_rate                : parameter
    RANGE s_reverseRate_midpoint            : parameter
    RANGE s_reverseRate_scale               : parameter
    RANGE s_reverseRate_shift               : parameter
    
    RANGE s_reverseRate_r                   : exposure
    RANGE s_timeCourse_TIME_SCALE           : parameter
    
    RANGE s_timeCourse_t                    : exposure
    RANGE s_q10Settings_q10Factor           : parameter
    RANGE s_q10Settings_experimentalTemp    : parameter
    RANGE s_q10Settings_TENDEGREES          : parameter
    
    RANGE s_q10Settings_q10                 : exposure
    RANGE f_instances                       : parameter
    
    RANGE f_alpha                           : exposure
    
    RANGE f_beta                            : exposure
    
    RANGE f_tau                             : exposure
    
    RANGE f_inf                             : exposure
    
    RANGE f_rateScale                       : exposure
    
    RANGE f_fcond                           : exposure
    RANGE f_forwardRate_rate                : parameter
    RANGE f_forwardRate_midpoint            : parameter
    RANGE f_forwardRate_scale               : parameter
    
    RANGE f_forwardRate_r                   : exposure
    RANGE f_reverseRate_rate                : parameter
    RANGE f_reverseRate_midpoint            : parameter
    RANGE f_reverseRate_scale               : parameter
    
    RANGE f_reverseRate_r                   : exposure
    RANGE f_timeCourse_TIME_SCALE           : parameter
    
    RANGE f_timeCourse_t                    : exposure
    RANGE f_q10Settings_q10Factor           : parameter
    RANGE f_q10Settings_experimentalTemp    : parameter
    RANGE f_q10Settings_TENDEGREES          : parameter
    
    RANGE f_q10Settings_q10                 : exposure
    RANGE s_timeCourse_ALPHA                : derived variable
    RANGE s_timeCourse_BETA                 : derived variable
    RANGE s_tauUnscaled                     : derived variable
    RANGE f_timeCourse_ALPHA                : derived variable
    RANGE f_timeCourse_BETA                 : derived variable
    RANGE f_tauUnscaled                     : derived variable
    RANGE conductanceScale                  : derived variable
    RANGE fopen0                            : derived variable
    
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (S) = (siemens)
    
}

PARAMETER {
    
    gmax = 0  (S/cm2)                       : Will be changed when ion channel mechanism placed on cell!
    
    conductance = 1.0E-5 (uS)
    s_instances = 1 
    s_forwardRate_rate = 0.033616737 (kHz)
    s_forwardRate_midpoint = 4.48754 (mV)
    s_forwardRate_scale = 6.81881 (mV)
    s_forwardRate_shift = 8.0000005E-5 (kHz)
    s_reverseRate_rate = 0.0016854445 (kHz)
    s_reverseRate_midpoint = -43.97494 (mV)
    s_reverseRate_scale = -0.10818 (mV)
    s_reverseRate_shift = 0.04752 (kHz)
    s_timeCourse_TIME_SCALE = 1 (ms)
    s_q10Settings_q10Factor = 3 
    s_q10Settings_experimentalTemp = 293.15 (K)
    s_q10Settings_TENDEGREES = 10 (K)
    f_instances = 1 
    f_forwardRate_rate = 0.31836 (kHz)
    f_forwardRate_midpoint = -80 (mV)
    f_forwardRate_scale = -62.52621 (mV)
    f_reverseRate_rate = 0.010140001 (kHz)
    f_reverseRate_midpoint = -83.3332 (mV)
    f_reverseRate_scale = 16.05379 (mV)
    f_timeCourse_TIME_SCALE = 1 (ms)
    f_q10Settings_q10Factor = 3 
    f_q10Settings_experimentalTemp = 293.15 (K)
    f_q10Settings_TENDEGREES = 10 (K)
}

ASSIGNED {
    
    gion   (S/cm2)                          : Transient conductance density of the channel? Standard Assigned variables with ionChannel
    v (mV)
    celsius (degC)
    temperature (K)
    ena (mV)
    ina (mA/cm2)
    
    
    s_forwardRate_r (kHz)                  : derived variable
    
    s_reverseRate_r (kHz)                  : derived variable
    
    s_timeCourse_ALPHA                     : derived variable
    
    s_timeCourse_BETA                      : derived variable
    
    s_timeCourse_t (ms)                    : conditional derived var...
    
    s_q10Settings_q10                      : derived variable
    
    s_rateScale                            : derived variable
    
    s_alpha (kHz)                          : derived variable
    
    s_beta (kHz)                           : derived variable
    
    s_fcond                                : derived variable
    
    s_inf                                  : derived variable
    
    s_tauUnscaled (ms)                     : derived variable
    
    s_tau (ms)                             : derived variable
    
    f_forwardRate_r (kHz)                  : derived variable
    
    f_reverseRate_r (kHz)                  : derived variable
    
    f_timeCourse_ALPHA                     : derived variable
    
    f_timeCourse_BETA                      : derived variable
    
    f_timeCourse_t (ms)                    : conditional derived var...
    
    f_q10Settings_q10                      : derived variable
    
    f_rateScale                            : derived variable
    
    f_alpha (kHz)                          : derived variable
    
    f_beta (kHz)                           : derived variable
    
    f_fcond                                : derived variable
    
    f_inf                                  : derived variable
    
    f_tauUnscaled (ms)                     : derived variable
    
    f_tau (ms)                             : derived variable
    
    conductanceScale                       : derived variable
    
    fopen0                                 : derived variable
    
    fopen                                  : derived variable
    
    g (uS)                                 : derived variable
    rate_s_q (/ms)
    rate_f_q (/ms)
    
}

STATE {
    s_q  
    f_q  
    
}

INITIAL {
    ena = 87.39
    
    temperature = celsius + 273.15
    
    rates()
    rates() ? To ensure correct initialisation.
    
    s_q = s_inf
    
    f_q = f_inf
    
}

BREAKPOINT {
    
    SOLVE states METHOD cnexp
    
    ? DerivedVariable is based on path: conductanceScaling[*]/factor, on: Component(id=GolgiNaR type=ionChannelHH), from conductanceScaling; null
    ? Path not present in component, using factor: 1
    
    conductanceScale = 1 
    
    ? DerivedVariable is based on path: gates[*]/fcond, on: Component(id=GolgiNaR type=ionChannelHH), from gates; Component(id=s type=gateHHratesTau)
    ? multiply applied to all instances of fcond in: <gates> ([Component(id=s type=gateHHratesTau), Component(id=f type=gateHHratesTau)]))
    fopen0 = s_fcond * f_fcond ? path based, prefix = 
    
    fopen = conductanceScale  *  fopen0 ? evaluable
    g = conductance  *  fopen ? evaluable
    gion = gmax * fopen 
    
    ina = gion * (v - ena)
    
}

DERIVATIVE states {
    rates()
    s_q' = rate_s_q 
    f_q' = rate_f_q 
    
}

PROCEDURE rates() {
    
    s_forwardRate_r = (  s_forwardRate_shift  +  s_forwardRate_rate  * ((v- s_forwardRate_midpoint )/ s_forwardRate_scale )  / (1 - (exp (-(v- s_forwardRate_midpoint )/ s_forwardRate_scale )))) ? evaluable
    s_reverseRate_r = (  s_reverseRate_shift  +  s_reverseRate_rate  * ((v- s_reverseRate_midpoint )/ s_reverseRate_scale )  / (1 - (exp (-(v- s_reverseRate_midpoint )/ s_reverseRate_scale )))) ? evaluable
    s_timeCourse_ALPHA = s_alpha  *  s_timeCourse_TIME_SCALE ? evaluable
    s_timeCourse_BETA = s_beta  *  s_timeCourse_TIME_SCALE ? evaluable
    if (( s_timeCourse_ALPHA  +  s_timeCourse_BETA ) < 1e-3)  { 
        s_timeCourse_t = 1000.0  *  s_timeCourse_TIME_SCALE ? evaluable cdv
    } else if (1/( s_timeCourse_ALPHA  +  s_timeCourse_BETA )  < ( 0.01 ))  { 
        s_timeCourse_t = 0.01  *  s_timeCourse_TIME_SCALE ? evaluable cdv
    } else  { 
        s_timeCourse_t = ( 1/( s_timeCourse_ALPHA  +  s_timeCourse_BETA )) *  s_timeCourse_TIME_SCALE ? evaluable cdv
    }
    
    s_q10Settings_q10 = s_q10Settings_q10Factor ^((temperature -  s_q10Settings_experimentalTemp )/ s_q10Settings_TENDEGREES ) ? evaluable
    ? DerivedVariable is based on path: q10Settings[*]/q10, on: Component(id=s type=gateHHratesTau), from q10Settings; Component(id=null type=q10ExpTemp)
    ? multiply applied to all instances of q10 in: <q10Settings> ([Component(id=null type=q10ExpTemp)]))
    s_rateScale = s_q10Settings_q10 ? path based, prefix = s_
    
    ? DerivedVariable is based on path: forwardRate/r, on: Component(id=s type=gateHHratesTau), from forwardRate; Component(id=null type=Golgi_NaR_gate_rate)
    s_alpha = s_forwardRate_r ? path based, prefix = s_
    
    ? DerivedVariable is based on path: reverseRate/r, on: Component(id=s type=gateHHratesTau), from reverseRate; Component(id=null type=Golgi_NaR_gate_rate)
    s_beta = s_reverseRate_r ? path based, prefix = s_
    
    s_fcond = s_q ^ s_instances ? evaluable
    s_inf = s_alpha /( s_alpha + s_beta ) ? evaluable
    ? DerivedVariable is based on path: timeCourse/t, on: Component(id=s type=gateHHratesTau), from timeCourse; Component(id=null type=Golgi_NaR_tau)
    s_tauUnscaled = s_timeCourse_t ? path based, prefix = s_
    
    s_tau = s_tauUnscaled  /  s_rateScale ? evaluable
    f_forwardRate_r = f_forwardRate_rate  * exp((v -  f_forwardRate_midpoint )/ f_forwardRate_scale ) ? evaluable
    f_reverseRate_r = f_reverseRate_rate  * exp((v -  f_reverseRate_midpoint )/ f_reverseRate_scale ) ? evaluable
    f_timeCourse_ALPHA = f_alpha  *  f_timeCourse_TIME_SCALE ? evaluable
    f_timeCourse_BETA = f_beta  *  f_timeCourse_TIME_SCALE ? evaluable
    if (( f_timeCourse_ALPHA  +  f_timeCourse_BETA ) < 1e-3)  { 
        f_timeCourse_t = 1000.0  *  f_timeCourse_TIME_SCALE ? evaluable cdv
    } else if (1/( f_timeCourse_ALPHA  +  f_timeCourse_BETA )  < ( 0.01 ))  { 
        f_timeCourse_t = 0.01  *  f_timeCourse_TIME_SCALE ? evaluable cdv
    } else  { 
        f_timeCourse_t = ( 1/( f_timeCourse_ALPHA  +  f_timeCourse_BETA )) *  f_timeCourse_TIME_SCALE ? evaluable cdv
    }
    
    f_q10Settings_q10 = f_q10Settings_q10Factor ^((temperature -  f_q10Settings_experimentalTemp )/ f_q10Settings_TENDEGREES ) ? evaluable
    ? DerivedVariable is based on path: q10Settings[*]/q10, on: Component(id=f type=gateHHratesTau), from q10Settings; Component(id=null type=q10ExpTemp)
    ? multiply applied to all instances of q10 in: <q10Settings> ([Component(id=null type=q10ExpTemp)]))
    f_rateScale = f_q10Settings_q10 ? path based, prefix = f_
    
    ? DerivedVariable is based on path: forwardRate/r, on: Component(id=f type=gateHHratesTau), from forwardRate; Component(id=null type=HHExpRate)
    f_alpha = f_forwardRate_r ? path based, prefix = f_
    
    ? DerivedVariable is based on path: reverseRate/r, on: Component(id=f type=gateHHratesTau), from reverseRate; Component(id=null type=HHExpRate)
    f_beta = f_reverseRate_r ? path based, prefix = f_
    
    f_fcond = f_q ^ f_instances ? evaluable
    f_inf = f_alpha /( f_alpha + f_beta ) ? evaluable
    ? DerivedVariable is based on path: timeCourse/t, on: Component(id=f type=gateHHratesTau), from timeCourse; Component(id=null type=Golgi_NaR_tau)
    f_tauUnscaled = f_timeCourse_t ? path based, prefix = f_
    
    f_tau = f_tauUnscaled  /  f_rateScale ? evaluable
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    
     
    rate_s_q = ( s_inf  -  s_q ) /  s_tau ? Note units of all quantities used here need to be consistent!
    
     
    
     
    
     
    
     
    
     
    rate_f_q = ( f_inf  -  f_q ) /  f_tau ? Note units of all quantities used here need to be consistent!
    
     
    
     
    
     
    
     
    
     
    
}

